# Generated by Django 4.2.30 on 2026-09-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('COFFEE', 'Coffee'), ('EQUIPMENT', 'Equipment'), ('ROASTING_MACHINE', 'Roasting machine'), ('ACCESSORY', 'Accessory')], default='COFFEE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('roaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.roaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(help_text='e.g. "250g / Whole bean"', max_length=120)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('grind', models.CharField(blank=True, choices=[('WHOLE_BEAN', 'Whole bean'), ('ESPRESSO', 'Espresso'), ('FILTER', 'Filter'), ('FRENCH_PRESS', 'French press'), ('TURKISH', 'Turkish')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('farm', models.CharField(blank=True, max_length=150)),
                ('process', models.CharField(blank=True, choices=[('WASHED', 'Washed'), ('NATURAL', 'Natural'), ('HONEY', 'Honey'), ('ANAEROBIC', 'Anaerobic'), ('WET_HULLED', 'Wet hulled')], max_length=20)),
                ('variety', models.CharField(blank=True, max_length=150)),
                ('roast_level', models.CharField(blank=True, choices=[('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('MEDIUM_DARK', 'Medium dark'), ('DARK', 'Dark')], max_length=20)),
                ('altitude_masl', models.PositiveIntegerField(blank=True, null=True)),
                ('tasting_notes', models.CharField(blank=True, max_length=300)),
                ('harvest_year', models.PositiveIntegerField(blank=True, null=True)),
                ('cupping_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_profile', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='variant_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(check=models.Q(('compare_at_price__isnull', True), ('compare_at_price__gt', models.F('price')), _connector='OR'), name='variant_compare_at_price_above_price'),
        ),
    ]
