# Generated by Django 4.2.30 on 2026-09-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_drop_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='roaster',
            name='bio_ar',
            field=models.TextField(blank=True),
        ),
    ]
