# Generated by Django 4.2.30 on 2026-09-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_description_ar_category_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.CharField(blank=True, choices=[('COFFEE', 'Coffee'), ('EQUIPMENT', 'Equipment'), ('ROASTING_MACHINE', 'Roasting machine'), ('ACCESSORY', 'Accessory')], max_length=20),
        ),
    ]
