# Generated by Django 4.2.30 on 2026-09-07 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HardwareProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_type', models.CharField(blank=True, choices=[('DRUM_ROASTER', 'Drum roaster'), ('FLUID_BED_ROASTER', 'Fluid-bed roaster'), ('SAMPLE_ROASTER', 'Sample roaster'), ('GRINDER', 'Grinder'), ('BREWER', 'Brewer'), ('KETTLE', 'Kettle'), ('OTHER', 'Other')], max_length=30)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hardware_profiles', to='catalog.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_profile', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
