# Generated by Django 4.2.30 on 2026-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_brand_hardwareprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
