# Generated by Django 4.2.30 on 2026-09-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_flavor_coffeeprofile_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flavors/'),
        ),
    ]
