# Generated by Django 4.2.30 on 2026-09-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_flavor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeprofile',
            name='variety',
        ),
    ]
