# Generated by Django 4.2.30 on 2026-09-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_coffeeprofile_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeprofile',
            name='farm',
        ),
    ]
