# Generated by Django 4.2.30 on 2026-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_coffeeprofile_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeprofile',
            name='tasting_notes_ar',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
