# Generated by Django 4.2.30 on 2026-09-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_drop_medium_dark_roast'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='origins/'),
        ),
    ]
